/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

/**
 *
 * @author Silvia
 */
public class menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuprincipal
     */
    public menuprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnpacientes = new javax.swing.JButton();
        btnprofesionales = new javax.swing.JButton();
        btnespecialidad = new javax.swing.JButton();
        btnturnos = new javax.swing.JButton();
        btnvolverinicio = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("para Consultorio Médico");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 350, 30));

        btnpacientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnpacientes.setText("PACIENTES");
        btnpacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpacientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnpacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 330, 40));

        btnprofesionales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnprofesionales.setText("PROFESIONALES");
        btnprofesionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofesionalesActionPerformed(evt);
            }
        });
        getContentPane().add(btnprofesionales, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 330, 40));

        btnespecialidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnespecialidad.setText("ESPECIALIDADES");
        btnespecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnespecialidadActionPerformed(evt);
            }
        });
        getContentPane().add(btnespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 330, 40));

        btnturnos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnturnos.setText("TURNOS");
        btnturnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnturnosActionPerformed(evt);
            }
        });
        getContentPane().add(btnturnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 330, 40));

        btnvolverinicio.setText("Volver a inicio");
        btnvolverinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverinicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnvolverinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 140, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Turnos ");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 290, 40));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpacientesActionPerformed
        pacienteCxE paciente = new pacienteCxE();
        paciente.setVisible(true);
       
    }//GEN-LAST:event_btnpacientesActionPerformed

    private void btnvolverinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverinicioActionPerformed
        bienvenido inicio = new bienvenido();
        inicio.setVisible(true);
    }//GEN-LAST:event_btnvolverinicioActionPerformed

    private void btnprofesionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofesionalesActionPerformed
       profesionales profesional = new profesionales();
       profesional.setVisible(true);
    }//GEN-LAST:event_btnprofesionalesActionPerformed

    private void btnespecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnespecialidadActionPerformed
        
        especialidades especialidad = new especialidades();
        especialidad.setVisible(true);
    }//GEN-LAST:event_btnespecialidadActionPerformed

    private void btnturnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnturnosActionPerformed
        turnos turno = new turnos();
        turno.setVisible(true);
    }//GEN-LAST:event_btnturnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnespecialidad;
    private javax.swing.JButton btnpacientes;
    private javax.swing.JButton btnprofesionales;
    private javax.swing.JButton btnturnos;
    private javax.swing.JButton btnvolverinicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
