/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

/**
 *
 * @author Silvia
 */
public class Turnos extends javax.swing.JFrame {

    /**
     * Creates new form turnos
     */
    public Turnos() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("TURNOS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        botCxEturnos = new javax.swing.JButton();
        botMenuPrincipal = new javax.swing.JButton();
        botAsigCanceTurnos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        botCxFturnos = new javax.swing.JButton();
        botAsigCanceConsuEspec = new javax.swing.JButton();
        botCxPturnos = new javax.swing.JButton();
        botCxProfTurnos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TURNOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 730, 50));

        botCxEturnos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botCxEturnos.setText("CONSULTA POR ESPECIALIDAD");
        getContentPane().add(botCxEturnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 610, 30));

        botMenuPrincipal.setText("VOLVER A MENU PRINCIPAL");
        botMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(botMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        botAsigCanceTurnos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botAsigCanceTurnos.setText("ASIGNACION Y CANCELACION DE TURNOS");
        botAsigCanceTurnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAsigCanceTurnosActionPerformed(evt);
            }
        });
        getContentPane().add(botAsigCanceTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 610, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/images (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 100, 100));

        botCxFturnos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botCxFturnos.setText("CONSULTA POR FECHA");
        getContentPane().add(botCxFturnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 610, 30));

        botAsigCanceConsuEspec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botAsigCanceConsuEspec.setText("ASIGNACION Y CANCELACION DE CONSULTORIOS Y ESPECIALIDADES");
        getContentPane().add(botAsigCanceConsuEspec, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 610, 30));

        botCxPturnos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botCxPturnos.setText("CONSULTA POR PACIENTE");
        getContentPane().add(botCxPturnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 610, 30));

        botCxProfTurnos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botCxProfTurnos.setText("CONSULTA POR PROFESIONAL");
        getContentPane().add(botCxProfTurnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 610, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/turnos.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botAsigCanceTurnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAsigCanceTurnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botAsigCanceTurnosActionPerformed

    private void botMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botMenuPrincipalActionPerformed
      
       MenuPrincipal menu = new MenuPrincipal();
       menu.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_botMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Turnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Turnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Turnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Turnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Turnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAsigCanceConsuEspec;
    private javax.swing.JButton botAsigCanceTurnos;
    private javax.swing.JButton botCxEturnos;
    private javax.swing.JButton botCxFturnos;
    private javax.swing.JButton botCxProfTurnos;
    private javax.swing.JButton botCxPturnos;
    private javax.swing.JButton botMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
